build: false
shallow_clone: true
platform:
  - x86
  - x64
clone_folder: c:\projects\mail

install:
  - cinst -y OpenSSL.Light
  - SET PATH=C:\Program Files\OpenSSL;%PATH%
  - sc config wuauserv start= auto
  - net start wuauserv
  - cinst -y php
  - cd c:\tools\php71
  - copy php.ini-production php.ini /Y
  - echo date.timezone="UTC" >> php.ini
  - echo extension_dir=ext >> php.ini
  - echo extension=php_openssl.dll >> php.ini
  - echo extension=php_intl.dll >> php.ini
  - echo extension=php_fileinfo.dll >> php.ini
  - SET PATH=C:\tools\php71;%PATH%
  - cd c:\projects\mail
  - php -r "readfile('http://getcomposer.org/installer');" | php
  - php composer.phar install --prefer-source --no-interaction

test_script:
  - cd c:\projects\mail
  - vendor/bin/phpunit --colors=always